import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";


import {
	Card,
	CardContent,
	CardDescription,
	CardFooter,
	CardHeader,
	CardTitle,
} from "@/components/ui/card";
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"


const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export function CreateCard(idNum: string){
	const id : number = parseInt(idNum);
	let idString :string = idNum.toString();
	if (id >= 1 && id < 10){
		idString = `#000${idString}`;
	} else if (id >= 10 && id < 100){
		idString = `#00${idString}`;
	} else if (id >= 100 && id < 1000){
		idString = `#0${idString}`;
	} else {
		idString = `#${idString}`;
	}
	
	const imgUrl :string = `https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/${id.toString()}.png`;
	return (<Card className="w-fit h-fit m-1">
		<CardHeader className="flex items-center justify-center">
		<img src={imgUrl} alt="Bulbersor" />
		</CardHeader>
		<CardContent>
		<CardTitle>Bulbasure</CardTitle>
		<CardDescription>{idString}</CardDescription>
		</CardContent>
		<CardFooter className="flex items-start justify-center">
			<Button className="m-1">Grass</Button>
			<Button className="m-1">Fire</Button>
		</CardFooter>
	</Card>);
}

export default function RootLayout({
	// children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
				<div className="flex flex-col items-center justify-center border-b border-solid border-gray-400">
					<h1 className="my-4 scroll-m-20 text-4xl font-extrabold tracking-tight lg:text-5xl">Pok&eacute;mon Browser</h1>
					<h4 className="text-gray-500">Search and find Pok&eacute;mon</h4>
				</div>

				<div className="grid grid-cols-6 grid-rows-1 gap-0 gap-y-0 my-5">
					<div className="col-start-2 row-start-1 col-span-4 flex items-center justify-between flex-wrap">
						<h3>Explore Pok&eacute;mon</h3>
						<div className="flex w-full max-w-sm items-center space-x-2 ">
							<Input type="search" placeholder="Find Pok&eacute;mon" />
							<Button type="submit">Search</Button>
						</div>
					</div>
				</div>
				<div className="grid grid-cols-6 grid-rows-3 gap-0 gap-y-0">
					{/* TODO: sort out height of top row */}
					<div className="col-start-2 row-start-1 col-span-4 flex items-center justify-between flex-wrap">
						{CreateCard("1")}
						{CreateCard("2")}
						{CreateCard("3")}
						{CreateCard("4")}
					</div>
					<div className="col-start-2 row-start-2 col-span-4 flex items-center justify-between flex-wrap ">
						{CreateCard("5")}
						{CreateCard("6")}
						{CreateCard("7")}
						{CreateCard("8")}
					</div>

					<div className="col-start-2 row-start-3 col-span-4 flex items-center justify-between flex-wrap">
						{CreateCard("9")}
						{CreateCard("10")}
						{CreateCard("11")}
						{CreateCard("12")}
					</div>
				</div>

				<div className="flex flex-row items-center justify-center my-5">
					<Button className="m-1">Back</Button>
					<Button className="m-1">Next</Button>
				</div>
				<div className="h-20 flex flex-col items-center justify-center border-t border-solid border-gray-400">
					<h4 className="text-gray-500">Thank you for using Pok&eacute;mon Browser!</h4>
				</div>

			</body>
		</html>
	);
}
